server:
  port: 8080

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/fin
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      pool-name: pool
      max-lifetime: 30000
      connection-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: 'update'

